### ISSUE TITLE
Evaluate Yarn

### ISSUE THREAD

**Issue by backflip** [unic/estatico#12]
Because **speed** (2-4x faster without a node_modules folder (depending on whether there is a local cache or not), 30x faster with a preexisting one – tested locally and on Jenkins) and **reliability** (`.yarn.lock` vs `npm-shrinkwrap.json`).

**Comment by backflip** [comment]
https://github.com/unic/estatico/compare/feature/ESTATICO-224-yarn?expand=1

**Comment by backflip** [comment]
Issue: `gulp-raster` seems not to be resolved correctly.

```
"gulp-raster@git://github.com/unic/gulp-raster.git#acd044d950d9ed65870b3c39cb6294a09174d166":
  version "0.1.0"
  resolved "git://github.com/unic/gulp-raster.git#acd044d950d9ed65870b3c39cb6294a09174d166"
  dependencies:
    gulp-util "~2.2.14"
    phridge "~1.1.0"
    through2 "*"
```

`phridge` should resolve to `^2.0.0`: https://github.com/unic/gulp-raster/commit/acd044d950d9ed65870b3c39cb6294a09174d166

See https://github.com/yarnpkg/yarn/pull/1393#issuecomment-257884141

**Comment by backflip** [comment]
Update: Tags seem to work: https://github.com/unic/estatico/commit/fd37dab39a4494fcb8c62e77ccb532bed17e3240

**Comment by orioltf** [comment]
PR awaiting feedback or reviews: #67

**Comment by backflip** [comment]
Dropped since recent `npm` versions fixed all of our issues.
