### ISSUE TITLE
Evaluate HTML validation

### ISSUE THREAD

**Issue by backflip** [unic/estatico#13]
[w3cjs](https://www.npmjs.com/package/w3cjs) looks promising, it detected some reasonable problems with our demo frontend: https://github.com/unic/estatico/commit/0201e89afacc64a7afd34b6508df9b6505d10f82

**Comment by backflip** [comment]
https://github.com/unic/estatico/compare/feature/ESTATICO-217-validate-html?expand=1

**Comment by d-simon** [comment]
Sadly, this implementation makes a request to w3c's online validator AND has a small (but reasonable) rate limit. Perhaps this could run with builds only plus i.e. with a pre-commit hook?

Also: What about _offline_ development? 🐴

**Comment by backflip** [comment]
Current status: We can use https://github.com/magnetikonline/dockerhtml5validator to run our own validator instance (both locally and remote, successfully tested). I will talk to our IT about spinning up an instance and document how to do it locally.

**Comment by backflip** [comment]
Thanks a lot for the pointers!

**Comment by backflip** [comment]
Introduced with https://github.com/unic/estatico-nou/tree/master/packages/estatico-w3c-validator
