### ISSUE TITLE
Module: Make this.log default logger

### ISSUE THREAD

**Issue by d-simon** [unic/estatico#18]
I propose a small change, which will make the logger (bows) more intuitive and easier to use:
From this: [/source/assets/js/helpers/module.js#L30](https://github.com/unic/estatico/blob/24d7fd974a9bb4360f9c6d6f3fbf0cbcab2ade4e/source/assets/js/helpers/module.js#L30)
```js
this.log = window.estatico.helpers.log;
```
To this:
```js
this.log = window.estatico.helpers.log(this.name);
```

With this change the logger can directly be used inside a module:
`this.log(importantLogData)` without having to "configure" it first.

---

Note: The log helper could still be exposed through the module, perhaps just with the "hidden" / "private" naming convention `this._log`
```js
// "private" naming convention - if you really need multiple
// loggers in a module, you will know where to look. :-)
this._log = window.estatico.helpers.log;
```

**Comment by orioltf** [comment]
Fixed in #48
