### ISSUE TITLE
Update to jQuery 3.x

### ISSUE THREAD

**Issue by caillou** [unic/estatico#21]
Is there a reason, we still use jQuery 2.x?

jQuery 3.x uses rAF for it's `.animate()` method, which in my opinion is enough of a feature to use it.

**Comment by backflip** [comment]
PR welcome! Apparently, there are some breaking changes regarding how we deal with attributes / properties, but since we don't have too much JS in the boilerplate, it should be feasible.

@marbor3, any inputs here?

**Comment by marbor3** [comment]
Hey!

Sorry for the delay but I had a terrible time management issues lately ... 

Never the less: https://github.com/unic/estatico/pull/45

We've been using this on a project for some time now - and like you said @backflip , there's not too much jQuery based code there so it looks like we needed just those two changes :)

**Comment by christiansany** [comment]
@backflip 
PR was merged, ticket can be closed :)

**Comment by orioltf** [comment]
Thanks!
