### ISSUE TITLE
Gulp 'media:imageversion' with watermarks

### ISSUE THREAD

**Issue by tobiasfrei** [unic/estatico#85]
To check the integrity of responsive images, watermarks on the generated images are required. The watermarks show the size of the images, similar to "placeholder. com". It would be desirable to add a flag for each image dimension, which determines whether the watermark is set or not.

**Comment by backflip** [comment]
`gm().drawText` seems to work locally. I'll check it on our CI, not sure whether there are additional graphic libraries needed.

**Comment by tobiasfrei** [comment]
very good input

**Comment by backflip** [comment]
@tobiasfrei, the linked PR worked fine on Teamcity:
![image](https://user-images.githubusercontent.com/654171/31991345-d804d4c0-b977-11e7-9d73-1809600bd2eb.png)

Text alignment inside the box isn't very nice, feel free to play around with the parameters...

**Comment by tobiasfrei** [comment]
we don't need a clean alignment. oriol wants to use it right away.

**Comment by backflip** [comment]
PR opened: https://github.com/unic/estatico/pull/87
